import type { Finding, Lead } from "./types";

export const sampleLeads: Lead[] = [
  { id: 1, agencyName: "Front Range Insurance Group", contactName: "Sarah Mitchell", carrier: "State Farm", city: "Fort Collins", state: "CO", website: "https://example.com", email: "sarah@example.com", phone: "+1 (970) 555-0142", status: "Report viewed", rating: 4.7, reviewCount: 86, score: 58, visibilityScore: 44, conversionScore: 52, technicalScore: 72, trustScore: 67, lastContactedAt: "2026-08-16T15:20:00Z", nextFollowUpAt: "2026-08-18T16:00:00Z", lastAuditAt: "2026-08-15T19:10:00Z", reportViews: 4, reportToken: "front-range-insurance", notes: "Viewed the report twice after the initial email." },
  { id: 2, agencyName: "Boulder Valley Coverage", contactName: "Michael Torres", carrier: "Allstate", city: "Boulder", state: "CO", website: "https://example.org", email: "michael@example.org", phone: "+1 (303) 555-0188", status: "Audit ready", rating: 4.3, reviewCount: 31, score: 64, visibilityScore: 61, conversionScore: 48, technicalScore: 78, trustScore: 70, lastContactedAt: null, nextFollowUpAt: null, lastAuditAt: "2026-08-17T15:30:00Z", reportViews: 0, reportToken: "boulder-valley-coverage", notes: "Audit is ready for review before outreach." },
  { id: 3, agencyName: "Mile High Risk Advisors", contactName: "Danielle Brooks", carrier: "Independent", city: "Denver", state: "CO", website: "https://example.net", email: "danielle@example.net", phone: "+1 (720) 555-0116", status: "Meeting booked", rating: 4.9, reviewCount: 124, score: 73, visibilityScore: 68, conversionScore: 71, technicalScore: 82, trustScore: 76, lastContactedAt: "2026-08-14T17:00:00Z", nextFollowUpAt: "2026-08-19T17:30:00Z", lastAuditAt: "2026-08-12T20:00:00Z", reportViews: 7, reportToken: "mile-high-risk", notes: "Discovery call booked for Wednesday." },
  { id: 4, agencyName: "Northern Colorado Insurance", contactName: "Eric Lawson", carrier: "Farmers", city: "Loveland", state: "CO", website: "https://example.edu", email: "eric@example.edu", phone: "+1 (970) 555-0194", status: "Follow-up due", rating: 4.1, reviewCount: 19, score: 49, visibilityScore: 42, conversionScore: 39, technicalScore: 61, trustScore: 55, lastContactedAt: "2026-08-12T14:10:00Z", nextFollowUpAt: "2026-08-17T15:00:00Z", lastAuditAt: "2026-08-11T22:00:00Z", reportViews: 1, reportToken: "northern-colorado-insurance", notes: "One report view. Follow up with the mobile CTA finding." },
  { id: 5, agencyName: "Pikes Peak Protection", contactName: "Amanda Chen", carrier: "State Farm", city: "Colorado Springs", state: "CO", website: "https://iana.org", email: "amanda@example.com", phone: "+1 (719) 555-0129", status: "Contacted", rating: 4.6, reviewCount: 58, score: 62, visibilityScore: 57, conversionScore: 54, technicalScore: 76, trustScore: 69, lastContactedAt: "2026-08-17T16:45:00Z", nextFollowUpAt: "2026-08-20T16:00:00Z", lastAuditAt: "2026-08-16T21:00:00Z", reportViews: 0, reportToken: "pikes-peak-protection", notes: "Initial audit email sent this afternoon." },
  { id: 6, agencyName: "Western Slope Benefit Partners", contactName: "Robert Hayes", carrier: "Independent", city: "Grand Junction", state: "CO", website: "https://example.com", email: "robert@example.com", phone: "+1 (970) 555-0167", status: "New", rating: 4.4, reviewCount: 42, score: 0, visibilityScore: 0, conversionScore: 0, technicalScore: 0, trustScore: 0, lastContactedAt: null, nextFollowUpAt: null, lastAuditAt: null, reportViews: 0, reportToken: "western-slope-benefit", notes: "New lead; audit has not been run." },
];

export const sampleFindings: Finding[] = [
  { category: "Visibility", severity: "High", title: "Local service relevance is unclear", evidence: "The primary page title does not identify a Colorado service area or a specific insurance need.", recommendation: "Rewrite the title and main heading around the agency’s primary market, location and highest-value services.", impact: "Clearer relevance can help searchers and search engines understand where and how the agency serves customers.", affectedUrl: "https://example.com", sortOrder: 1 },
  { category: "Conversion", severity: "High", title: "No dominant quote-request path", evidence: "The first viewport does not present a single, visually dominant quote or consultation action.", recommendation: "Add one primary Request a Quote action in the header and first viewport, with a persistent mobile call action.", impact: "Visitors have fewer decisions to make and a clearer route from research to contact.", affectedUrl: "https://example.com", sortOrder: 2 },
  { category: "Trust", severity: "Medium", title: "Trust evidence appears too late", evidence: "Ratings, carrier credentials and team information are not visible near the initial offer.", recommendation: "Move rating, review count and local team credentials directly beneath the opening value proposition.", impact: "Early trust signals reduce uncertainty before a prospect is asked to share contact information.", affectedUrl: "https://example.com", sortOrder: 3 },
];
