import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const leads = sqliteTable("leads", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  agencyName: text("agency_name").notNull(),
  contactName: text("contact_name").notNull().default(""),
  carrier: text("carrier").notNull().default("Independent"),
  city: text("city").notNull(),
  state: text("state").notNull().default("CO"),
  website: text("website").notNull(),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  status: text("status").notNull().default("Identified"),
  rating: real("rating"),
  reviewCount: integer("review_count").notNull().default(0),
  googleProfileUrl: text("google_profile_url").notNull().default(""),
  googlePrimaryCategory: text("google_primary_category").notNull().default(""),
  googleReviewRecencyDays: integer("google_review_recency_days").notNull().default(0),
  googleResponseRate: integer("google_response_rate").notNull().default(0),
  googlePhotoCount: integer("google_photo_count").notNull().default(0),
  googlePostRecencyDays: integer("google_post_recency_days").notNull().default(0),
  googleProfileCompleteness: integer("google_profile_completeness").notNull().default(0),
  googleNapConsistent: integer("google_nap_consistent", { mode: "boolean" }).notNull().default(false),
  googleReviewedAt: text("google_reviewed_at"),
  score: integer("score").notNull().default(0),
  visibilityScore: integer("visibility_score").notNull().default(0),
  conversionScore: integer("conversion_score").notNull().default(0),
  technicalScore: integer("technical_score").notNull().default(0),
  trustScore: integer("trust_score").notNull().default(0),
  lastContactedAt: text("last_contacted_at"),
  nextFollowUpAt: text("next_follow_up_at"),
  lastAuditAt: text("last_audit_at"),
  reportViews: integer("report_views").notNull().default(0),
  reportToken: text("report_token").notNull().unique(),
  fitScore: integer("fit_score").notNull().default(0),
  needScore: integer("need_score").notNull().default(0),
  intentScore: integer("intent_score").notNull().default(0),
  urgencyScore: integer("urgency_score").notNull().default(0),
  reachabilityScore: integer("reachability_score").notNull().default(0),
  qualificationStatus: text("qualification_status").notNull().default("Unqualified"),
  businessObjective: text("business_objective").notNull().default(""),
  painPoint: text("pain_point").notNull().default(""),
  currentProvider: text("current_provider").notNull().default(""),
  decisionMaker: text("decision_maker").notNull().default(""),
  budgetRange: text("budget_range").notNull().default(""),
  desiredTimeline: text("desired_timeline").notNull().default(""),
  nextCommittedStep: text("next_committed_step").notNull().default(""),
  objection: text("objection").notNull().default(""),
  lossReason: text("loss_reason").notNull().default(""),
  dealValue: integer("deal_value").notNull().default(0),
  sequenceStatus: text("sequence_status").notNull().default("Not started"),
  sequenceStep: integer("sequence_step").notNull().default(0),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const audits = sqliteTable("audits", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  leadId: integer("lead_id").notNull(),
  website: text("website").notNull(),
  score: integer("score").notNull(),
  visibilityScore: integer("visibility_score").notNull(),
  conversionScore: integer("conversion_score").notNull(),
  technicalScore: integer("technical_score").notNull(),
  trustScore: integer("trust_score").notNull(),
  pagesAudited: integer("pages_audited").notNull().default(1),
  responseStatus: integer("response_status"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditFindings = sqliteTable("audit_findings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  auditId: integer("audit_id").notNull(),
  category: text("category").notNull(),
  severity: text("severity").notNull(),
  title: text("title").notNull(),
  evidence: text("evidence").notNull(),
  recommendation: text("recommendation").notNull(),
  impact: text("impact").notNull(),
  affectedUrl: text("affected_url").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
});

export const reportEvents = sqliteTable("report_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  leadId: integer("lead_id").notNull(),
  eventType: text("event_type").notNull(),
  metadata: text("metadata").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const activities = sqliteTable("activities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  leadId: integer("lead_id").notNull(),
  activityType: text("activity_type").notNull(),
  description: text("description").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const proposals = sqliteTable("proposals", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  leadId: integer("lead_id").notNull(),
  token: text("token").notNull().unique(),
  offerId: text("offer_id").notNull(),
  title: text("title").notNull(),
  service: text("service").notNull(),
  outcome: text("outcome").notNull(),
  scope: text("scope").notNull(),
  deliverables: text("deliverables").notNull().default("[]"),
  price: integer("price").notNull(),
  timeline: text("timeline").notNull(),
  status: text("status").notNull().default("Sent"),
  viewCount: integer("view_count").notNull().default(0),
  expiresAt: text("expires_at").notNull(),
  acceptedAt: text("accepted_at"),
  signerName: text("signer_name").notNull().default(""),
  signerEmail: text("signer_email").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const aiRuns = sqliteTable("ai_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  leadId: integer("lead_id").notNull(),
  action: text("action").notNull(),
  model: text("model").notNull(),
  status: text("status").notNull().default("Draft"),
  result: text("result").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
